name:                haru2036com
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/haskell-and-elm#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - text
  - containers
  - elm-export
  - http-api-data
  - servant
  - servant-ede
  - servant-elm
  - servant-server
  - stm
  - transformers

library:
  source-dirs:      src
  exposed-modules:
    - Site
    - Model
  other-modules: []
